setup_model:
  model_id: "Qwen/Qwen3-1.7B"
  max_seq_length: 4096
  dtype: null
  full_finetuning: true

hyperparameters:
  per_device_train_batch_size: 16
  gradient_accumulation_steps: 4
  # max_steps: 120
  warmup_steps: 10
  learning_rate: 1e-5
  embedding_learning_rate: 1e-5
  logging_steps: 1
  optim: "adamw_8bit"
  weight_decay: 0.01
  lr_scheduler_type: "linear"
  seed: 42
  output_dir: "outputs"
  report_to: "none"
  num_train_epochs: 1


unsloth_trainer_config:
  dataset_text_field: "text"
  max_seq_length: 4096
  dataset_num_proc: 2